"""another migration

Revision ID: 97b6a4671736
Revises: 774efd73a0f1
Create Date: 2019-04-24 15:50:05.523862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b6a4671736'
down_revision = '774efd73a0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime', sa.Column('category', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crime', 'category')
    # ### end Alembic commands ###
