"""migration three

Revision ID: dc992e7d2445
Revises: 97b6a4671736
Create Date: 2019-04-24 15:56:21.931386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc992e7d2445'
down_revision = '97b6a4671736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('crime', 'logintude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime', sa.Column('logintude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('crime', 'longitude')
    # ### end Alembic commands ###
